- name : OverWrite
  hosts: local
  connection: local
  vars_files:
  - vars.yaml

  tasks: 
    - name: print something
      vars: 
        Course: "Devops Course"
      ansible.builtin.debug:
        msg: "I love to Learn {{Course}} from {{Name}} accepted challenge {{Duration}}"