- name: variables preference
  hosts: local
  connection: local
  vars:
    Name: Ansible from playbook
  vars_files:
  - vars.yaml
  vars_prompt:
  - ame: Name
    prompt: Enter your name
    private: false
  tasks:
  - name: print Name
    vars:
      Name: Ansible from task 
    ansible.builtin.debug:
      msg: "Hi {{ Name }}"