- name : condition arithmetic
  hosts: local
  connection: local
  vars:
    a: 10
    b: 20
  tasks:
  - name: print condition
    ansible.builtin.debug:
      msg: "{{ a + b }}"
    when: a + b > 10